# syntax=docker/dockerfile:1
FROM mambaorg/micromamba:focal

USER root
RUN apt-get update && \
  apt-get install -yq tzdata && \
  ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata
USER $MAMBA_USER

RUN <<EOF cat > assembly.yml
name: assembly
channels:
  - bioconda
  - conda-forge
dependencies:
  - megahit=1.2.9
  - quast=5.2.0
EOF

RUN micromamba install -y -n base -f assembly.yml && \
  micromamba clean --all --yes

ENV PATH "/opt/conda/bin:$PATH"
