# syntax=docker/dockerfile:1
FROM mambaorg/micromamba:focal

USER root
RUN apt-get update && \
  apt-get install -yq tzdata && \
  ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata
USER $MAMBA_USER

RUN <<EOF cat > sourmash.yml
name: sourmash
channels:
  - bioconda
  - conda-forge
dependencies:
  - sourmash=4.6.1
  - khmer=3.0.0a3
EOF

RUN micromamba install -y -n base -f sourmash.yml && \
  micromamba clean --all --yes

ENV PATH "/opt/conda/bin:$PATH"
