# syntax=docker/dockerfile:1
FROM mambaorg/micromamba:focal

USER root
RUN apt-get update && \
  apt-get install -yq tzdata && \
  ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata
USER $MAMBA_USER

RUN <<EOF cat > prodigal.yml
name: prodigal
channels:
  - bioconda
dependencies:
  - prodigal=2.6.3
EOF

RUN micromamba install -y -n base -f prodigal.yml && \
  micromamba clean --all --yes

ENV PATH "/opt/conda/bin:$PATH"
