
# How are the final results published?
# By default, files are copied from the work-dir.
# Valid settings: "copy", "move", "link", "symlink"
## Attention: "link" does not work on all filesystems, such as some /scratch volumes
publish_mode: "copy"

# Where should the results end up?
# One folder for the statistics
# One for the preprocessed reads
# One for the classification results
# One for the assemblies and bins?
outdir: "./output"

#########################################################################
# Preprocessing parameters

# location of the host genome
# Important! It needs to be indexed already
host_genome_location: "/labs/asbhatt/wirbel/utils/host_genome/hg38/"
bwa_index_base: "hg38.fa"

# trim galore
trimgalore_quality:  30
trimgalore_min_read_length: 60
trimgalore_start_trim: 0
trimgalore_end_trim: 0


#########################################################################
# Classification parameters

run_motus: true
run_metaphlan: true
run_phanta: true

# parameters for mOTUs2
motus_map_mgs_cutoff: 2
motus_min_len_align_length: 75

# parameters for metaphlan
metaphlan_db_path: "/labs/asbhatt/wirbel/utils/metaphlan_db/"

# parameters for phanta
